name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  pre-commit:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirement.txt
            **/test-requirement.txt

      - name: Installing dependencies.
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirement.txt
          python -m pip install -r tests/test-requirement.txt

      - name: Checking code formatting.
        uses: chartboost/ruff-action@v1
        with:
          args: format --check

      - name: Running linter.
        uses: chartboost/ruff-action@v1

      - name: Running static types checker.
        run: |
          mypy
